### ISSUE TITLE
恳求

### ISSUE THREAD

**Issue by ljcyx236** [Mondayfirst/XXQG_TiKu#1]
恳求:
恳求保留原序列版本(未作列表排序), 保留可选答案ABCD序号(未去除可选答案的序号), 不需要保证题目的唯一性, 原汁原味版本答案位置不会错位, 看题时候也能知道答案在哪个位置, 恳请放出多个版本, 如不方便公开, 可否私信来, 谢谢!

**Comment by Mondayfirst** [comment]
收到，尽快更新

**Comment by ljcyx236** [comment]
最简单要求, "保留挑战答题原顺序 ", 非常感谢!

**Comment by ljcyx236** [comment]
如期而至, 非常感谢, 最简单要求, 希望"保留挑战答题原顺序 ", 再次感谢!

**Comment by Mondayfirst** [comment]
"题库预览_标号版"保留了挑战答题原顺序
"题库预览_排序版"为挑战答题排序后的顺序
