### ISSUE TITLE
请教作者

### ISSUE THREAD

**Issue by dang1013** [mondayfirst/XXQG_TiKu#10]
作者能不能推荐个答题脚本啊，给个链接或者联系方式或邮箱。

**Comment by Mondayfirst** [comment]
全站搜索关键字`xxqg`，`xuexiqiangguo`，`学习强国`，并按照最近更新时间排序

**Comment by Mondayfirst** [comment]
在他们脚本里挑战答题这块，取消连对5道的限制就好了。
将连对5道就退出 改为 循环答题错了重来。

**Comment by dang1013** [comment]
@Mondayfirst 感谢作者！
