### ISSUE TITLE
今天（4.28）更新的题库有问题

### ISSUE THREAD

**Issue by CuteLicense** [mondayfirst/XXQG_TiKu#12]
"人们平常打点滴（吊针）用的生理盐水（氯化钠注射液）浓度是        %。||||": "", "6亿吨，其中80%以上的贡献来自        。|人造林|天然林": "天然林"

这个应该是有问题

**Comment by wangwang-code** [comment]
跑建立题库_autoJS.js  到1127题答错了， 没看清题目只有：  古代 金 铸造 。印象里只有这些了 不知道远程题库有没有成功提交正确的答案上去

**Comment by Mondayfirst** [comment]
@CuteLicense 感谢，确实有问题，应该是之前提交问题的时候界面卡住了，没有答案的文本。不过后面有一道完整的正确的题目，实际使用时并不影响。

**Comment by Mondayfirst** [comment]
@wangwang-code 应该是提交了，除非网断了。

**Comment by Mondayfirst** [comment]
> "人们平常打点滴（吊针）用的生理盐水（氯化钠注射液）浓度是        %。||||": "", "6亿吨，其中80%以上的贡献来自        。|人造林|天然林": "天然林"
> 
> 这个应该是有问题

已经删除该错误题目
