### ISSUE TITLE
题库依然存在较多重复、答案格式不正确、题目标题中缺少答案的空格占位符等等

### ISSUE THREAD

**Issue by yishibakaien** [Mondayfirst/XXQG_TiKu#14]
你可以使用我清洗过的数据，稍微好一点，不能完全排除没有问题
issue 中不能上传 .json 文件我用 .txt 给你，数据源是你的 `题库_排序版.json`
[source.txt](https://github.com/Mondayfirst/XXQG_TiKu/files/8628488/source.txt)

**Comment by Mondayfirst** [comment]
收到，感谢，以下是其它重复题目。重复次数少的题目，答案有微小区别，我看了看，可能是APP的原因，就不删了吧。
- `选择词语的正确词形        。`
- `选择词语的正确词形        。 来源：《现代汉语词典》（第七版）（商务印书馆2020年版）`
- `选择正确的读音        。`
- `选择正确的读音        。 来源：《现代汉语词典》（第七版）（商务印书馆2020年版）`
- `下列词形正确的是        。 来源：《现代汉语词典》（商务印书馆2016年第7版）`
- `选择正确的读音        。 来源：《现代汉语词典（第七版）》（商务印书馆2017年版）`
- `2020年10月14日，习近平在深圳经济特区建立四十周年庆祝大会上指出，        是改革开放的排头兵、先行地、实验区，是建立经济特区时间最早、数量最多的省份。 来源：《论中国共产党历史》（中央文献出版社2021年版）`
- `我国宪法规定，国家在社会主义初级阶段的基本经济制度是        。`
- `下列选项中，在春节档上映的电影是        。`
- `冰壶又叫“冰上溜石”，为圆壶状，由        制成。`
- `下列不属于二十四史的是        。`
- `根据《中华人民共和国传染病防治法》，甲类传染病是指：        。`
- `1935年3月底，项英、陈毅等率领约300人，先后到达赣粤边地区，同当地党组织和游击队会合，以        为中心，坚持艰苦的游击战争。 来源：《中国共产党的九十年》（中共党史出版社、党建读物出版社2016年版）`
- `驱逐舰采用平甲板船型的优点是        。`
- `陆游的诗句“纸上得来终觉浅，绝知此事要躬行”描写的是        。`
- `2006年7月1日，全长1956公里的        全线通车，结束了西藏不通铁路的历史，有力推动了雪域高原的跨越式发展和各族人民生活的改善，成为西藏经济社会发展的“输氧线”。 来源：《中国共产党简史》（人民出版社、中共党史出版社2021年版）`
- `地震发生时，身处高楼，下列选项中正确的自救防护措施是        。`

**Comment by yishibakaien** [comment]
> 收到，感谢，以下是其它重复题目。重复次数少的题目，答案有微小区别，我看了看，可能是APP的原因，就不删了吧。
> 
> * `选择词语的正确词形        。`
> * `选择词语的正确词形        。 来源：《现代汉语词典》（第七版）（商务印书馆2020年版）`
> * `选择正确的读音        。`
> * `选择正确的读音        。 来源：《现代汉语词典》（第七版）（商务印书馆2020年版）`
> * `下列词形正确的是        。 来源：《现代汉语词典》（商务印书馆2016年第7版）`
> * `选择正确的读音        。 来源：《现代汉语词典（第七版）》（商务印书馆2017年版）`
> * `2020年10月14日，习近平在深圳经济特区建立四十周年庆祝大会上指出，        是改革开放的排头兵、先行地、实验区，是建立经济特区时间最早、数量最多的省份。 来源：《论中国共产党历史》（中央文献出版社2021年版）`
> * `我国宪法规定，国家在社会主义初级阶段的基本经济制度是        。`
> * `下列选项中，在春节档上映的电影是        。`
> * `冰壶又叫“冰上溜石”，为圆壶状，由        制成。`
> * `下列不属于二十四史的是        。`
> * `根据《中华人民共和国传染病防治法》，甲类传染病是指：        。`
> * `1935年3月底，项英、陈毅等率领约300人，先后到达赣粤边地区，同当地党组织和游击队会合，以        为中心，坚持艰苦的游击战争。 来源：《中国共产党的九十年》（中共党史出版社、党建读物出版社2016年版）`
> * `驱逐舰采用平甲板船型的优点是        。`
> * `陆游的诗句“纸上得来终觉浅，绝知此事要躬行”描写的是        。`
> * `2006年7月1日，全长1956公里的        全线通车，结束了西藏不通铁路的历史，有力推动了雪域高原的跨越式发展和各族人民生活的改善，成为西藏经济社会发展的“输氧线”。 来源：《中国共产党简史》（人民出版社、中共党史出版社2021年版）`
> * `地震发生时，身处高楼，下列选项中正确的自救防护措施是        。`

好的，感谢，非常感谢你提供的题库
