### ISSUE TITLE
这个题库怎么能够转换成sqlite库？

### ISSUE THREAD

**Issue by lnliwei** [mondayfirst/XXQG_TiKu#15]

**Comment by Mondayfirst** [comment]
- 不清楚你要转换的sqlite库需要什么样的查询条件，建议查看 #3 

问的还挺多，先给一个Python的参考教程，回头再写个简单的示例吧
> [SQLite - Python|菜鸟教程](https://www.runoob.com/sqlite/sqlite-python.html)

**Comment by PutinYpa** [comment]
我用写了一个转换程序，要吗？

**Comment by PutinYpa** [comment]
> 我用qt写了一个转换程序，要吗？ 上传到网盘了，自取，要把json文件名改为 tiku.json, 放到可执行文件相同目录就可以。 数据库结构：tiku ( question option1 option2 option3 option4 option5 option6 answer ) 链接：https://pan.baidu.com/s/1EiI-HIhl8dvuWMdlkKzoEw 提取码：t484

源码也提供一下吧：
链接：https://pan.baidu.com/s/15xiKeeNimwvMbGuNBJsgTQ 
提取码：4fs7

**Comment by PutinYpa** [comment]
转换程序比较大是因为qt编译的静态程序就是比较大，这还是用upx压缩过的，否则更大。不放心，用源码自己编译哦 : )
