### ISSUE TITLE
建立题库_autoJS.js 和最新的题库总是错

### ISSUE THREAD

**Issue by wangwang-code** [Mondayfirst/XXQG_TiKu#16]
如题，连续不到3道题就错，而且题库里明明有题还是错误，有对于的答案还是一直选A 以前用都没这个问题

**Comment by Mondayfirst** [comment]
> 使用一开始提交`建立题库_autoJS.js`的题库就能一直答

- 05.05日晚，#14 删除格式错误题目时直接拷贝txt文档然后覆盖。
- 05.06日早，回退了版本，手动删题，题库现在可正常答题。

错误原因分析：
 复制时题目都一样，光看看不出异常来，但实际上uicode字符有区别，所以一直报错。题库使用之前的或现在的版本都可以，最近没有新题目，APP里还是2614道题。
