### ISSUE TITLE
请问如何使用脚本进行自动挑战答题，谢谢

### ISSUE THREAD

**Issue by Techaben** [mondayfirst/XXQG_TiKu#17]
请问如何使用脚本进行自动挑战答题，谢谢，找不到相应的运行脚本，只能查询使用，感觉有点暴殄天物

**Comment by mondayfirst** [comment]
使用方式可参考：[建立题库_autoJS.js](https://github.com/mondayfirst/XXQG_TiKu/blob/main/%E5%BB%BA%E7%AB%8B%E9%A2%98%E5%BA%93_autoJS.js)
