### ISSUE TITLE
四人赛和双人赛

### ISSUE THREAD

**Issue by Akira-TL** [mondayfirst/XXQG_TiKu#18]
大佬的功能很好用,自己测试了下autojs,挑战答题很香,但是不知道四人赛和双人赛为什么不能刷,是只能刷挑战答题吗?希望能开发四人赛和双人赛的刷题功能

**Comment by wangwang-code** [comment]
从理论上就不可行  题目选项被隐藏 OCR准确率感人 时不时弹滑块

**Comment by guyun1122** [comment]
> 

坐等吧，哈哈。

**Comment by JLGB** [comment]
忘了吧，四人 和 双人答题一去不返了，答题的都开启隐私模式了，截图GG了

**Comment by mondayfirst** [comment]
> 忘了吧，四人 和 双人答题一去不返了，答题的都开启隐私模式了，截图GG了

@JLGB 可使用2.33学习强国，并在应用商店忽略该软件的更新

**Comment by McMug2020** [comment]
Fork供参考 https://github.com/McMug2020/XXQG_TiKu
