### ISSUE TITLE
key有时候无效

### ISSUE THREAD

**Issue by kongbiao** [Mondayfirst/XXQG_TiKu#2]
问题|答案1|答案2|...:正确答案。问题与可选答案之间以|符号分隔。
现在答案顺序不一样了，拼出来的key，找不到value

**Comment by Mondayfirst** [comment]
根据你的说明，有以下可能：
1. 未使用列表排序功能。如果同一题目下，答案相同但是乱序，那么使用列表排序后答案的组合顺序唯一，对应的key值也唯一。
2. 题库未包含此题目。本题库每月底一更新，官方每月都会更新挑战答题题库，增删题目，对于新题目便没有相应的key。但每月的新题目很少，建议跳过该题目或随机一个答案重新答题，挑战答题两次5道题都遇上新题目的概率很低。

说明: 四人赛和双人赛的题库囊括挑战答题题库，额外有一些题目，遇上新题目的概率相对更大。然而官方限制每天的比赛次数且答对5道题自动结束比赛，难以获得完整题库。此种情况目前有思路解决，等闲时实践。

题库里的每个键值对都是作者多次刷穿挑战答题题库后保存的，如不符合以上情况，可以补充信息。

**Comment by kongbiao** [comment]
是的，我也用AccessibilibityService跑了一遍挑战答题，筛出来几道新题：


"在党的领导下，以1922年1月香港海员罢工为起点，1923年2月&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;为终点，掀起了中国工人运动第一次高潮。 来源：《中国共产党简史》（人民出版社、中共党史出版社2021年版）|安源路矿工人大罢工|京汉铁路工人罢工|开滦煤矿工人大罢工": "京汉铁路工人罢工",
"中国共产党第一次全国代表大会选举产生的中央局书记是&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;。 来源：《中国共产党简史》（人民出版社、中共党史出版社2021年版）|董必武|陈独秀|周恩来|毛泽东": "陈独秀",
"北伐战争时期工人运动发展的最高峰是&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;。 来源：《中国共产党简史》（人民出版社、中共党史出版社2021年版）|省港大罢工|开滦煤矿工人大罢工|香港海员大罢工|上海工人第三次武装起义": "上海工人第三次武装起义",
"选择词语的正确词形&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;。|不醒人事|不省人事": "不省人事",
"“政权是由枪杆子中取得的”的著名论断是毛泽东在&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;上提出的。 来源：《中国共产党简史》（人民出版社、中共党史出版社2021年版）|中共三大|八七会议|中共四大|遵义会议": "八七会议",
"选择词语的正确词形&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;。|精疲力竭|筋疲力竭": "精疲力竭",
"1938年9月至11月，党的扩大的六届六中全会在&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;举行。 来源：《中国共产党简史》（人民出版社、中共党史出版社2021年版）|重庆|延安|西安|长沙": "延安",
"解放战争期间，&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;解放了东北全境。 来源：《中国共产党简史》（人民出版社、中共党史出版社2021年版）|平津战役|辽沈战役|淮海战役": "辽沈战役",
"1928年6月至7月，中国共产党第六次全国代表大会在&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;举行。 来源：《中国共产党简史》（人民出版社、中共党史出版社2021年版）|北京|上海|莫斯科": "莫斯科",
"中华苏维埃第一次全国代表大会于&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;在江西瑞金召开。 来源：《中国共产党简史》（人民出版社、中共党史出版社2021年版）|1931年11月|1932年10月|1933年9月": "1931年11月",
"1920年8月，共产党早期组织在上海《新青年》编辑部成立，&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;任书记。 来源：《中国共产党简史》（人民出版社、中共党史出版社2021年版）|李大钊|陈独秀|董必武|毛泽东": "陈独秀",
"李大钊在&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;中系统介绍了马克思主义理论，标志着马克思主义在中国进入比较系统的传播阶段。 来源：《中国共产党简史》（人民出版社、中共党史出版社2021年版）|《庶民的胜利》|《法俄革命之比较观》|《我的马克思主义观》|《布尔什维主义的胜利》": "《我的马克思主义观》",
"第一次国共合作正式形成的标志是&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;。 来源：《中国共产党简史》（人民出版社、中共党史出版社2021年版）|中共三大的召开|黄埔军校的建立|国民党一大的召开|广东国民政府的建立": "国民党一大的召开",
"把毛泽东思想确立为党的指导思想并写入党章的会议是&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;。 来源：《中国共产党简史》（人民出版社、中共党史出版社2021年版）|遵义会议|党的六大|党的七大|党的八大": "党的七大"


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mondayfirst/XXQG_TiKu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月31日(星期六) 上午9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mondayfirst/XXQG_TiKu] key有时候无效 (#2)





 
根据你的说明，有以下可能：
  
未使用列表排序功能。如果同一题目下，答案相同但是乱序，那么使用列表排序后答案的组合顺序唯一，对应的key值也唯一。
 
题库未包含此题目。本题库每月底一更新，官方每月都会更新挑战答题题库，增删题目，对于新题目便没有相应的key。但每月的新题目很少，建议跳过该题目或随机一个答案重新答题，挑战答题两次5道题都遇上新题目的概率很低。
  
说明: 四人赛和双人赛的题库囊括挑战答题题库，额外有一些题目，遇上新题目的概率相对更大。然而官方限制每天的比赛次数且答对5道题自动结束比赛，难以获得完整题库。此种情况目前有思路解决，等闲时实践。
 
题库里的每个键值对都是作者多次刷穿挑战答题题库后保存的，如不符合以上情况，可以补充信息。

**Comment by Mondayfirst** [comment]
简单对照了下，筛出来的题目没有经过列表排序。部分已在题库中；部分是新题，可能最近官方又更新了几道。
建议进行列表排序，保证题目唯一性。干脆把答案没排序的题库也上传吧
