### ISSUE TITLE
题库中个别题目答案有误

### ISSUE THREAD

**Issue by Tq7** [mondayfirst/XXQG_TiKu#21]
"补全唐代诗人王维《鹿柴》诗句：返景入深林，复照        上。 来源：参见《钱锺书选唐诗》（人民文学出版社2020年版）|青石|青苔": "青石"
"武昌鱼早在1700多年前的三国时期，已饮誉大江南北。毛主席的著名诗句“         ”，让武昌鱼声名大噪。|才饮长沙水，又食武昌鱼|秋来倍忆武昌鱼，梦著只在巴陵道|迢迢建业水，中有武昌鱼": "秋来倍忆武昌鱼，梦著只在巴陵道"
"在气动力布局中，最基本的是机翼和尾翼的选择与布置，其中        是飞机的辅助升力面，起平衡稳定、控制飞行姿态的作用。 来源：《十万个为什么》（第六版）（上海世纪出版股份有限公司少年儿童出版社2014年版）|尾翼|机翼": "机翼"
"民事强制执行对象        被执行人的财产或行为，不包括被执行人及其扶养家属的生活必需费用和物品，对被执行人的人身不得采取强制措施；当事人申请执行与法院依职权主动执行相结合；强制执行与说服教育相结合；法院执行与有关单位、个人协助执行相结合。 来源：《中国大百科全书》（第三版网络版）（中国大百科全书出版社）|仅限于|包括但不限于": "包括但不限于"

**Comment by mondayfirst** [comment]
因APP存在变动（下划线处前后随机加空格），由此产生了一些新题目。
经查，确实有误，且类似错误较多，将重新检查清洗题库，并对外关闭题目新增接口。感谢指出！

**Comment by Tq7** [comment]
"补全唐代诗人王维《鹿柴》诗句：返景入深林，复照        上。来源：参见《钱锺书选唐诗》（人民文学出版社2020年版）|青石|青苔": "青石"
"在气动力布局中，最基本的是机翼和尾翼的选择与布置，其中        是飞机的辅助升力面，起平衡稳定、控制飞行姿态的作用。来源：《十万个为什么》（第六版）（上海世纪出版股份有限公司少年儿童出版社2014年版）|尾翼|机翼": "机翼"
"民事强制执行对象        被执行人的财产或行为，不包括被执行人及其扶养家属的生活必需费用和物品，对被执行人的人身不得采取强制措施；当事人申请执行与法院依职权主动执行相结合；强制执行与说服教育相结合；法院执行与有关单位、个人协助执行相结合。来源：《中国大百科全书》（第三版网络版）（中国大百科全书出版社）|仅限于|包括但不限于": "包括但不限于"

以上三题的答案还是错的，期待改正！
函数 click_answer_radio_button() 中的 var true_ans = answers[0] 是否有误？

**Comment by mondayfirst** [comment]
@Tq7 
> 函数 click_answer_radio_button() 中的 var true_ans = answers[0] 是否有误？

有误！感谢指出！该BUG会使脚本必须在答错时才能获取正确答案，已紧急修复。

> 以上三题的答案还是错的，期待改正！

为保证新脚本使用，先放出一版题库。题库里老APP版本题目答案全部正确，但新APP版本的题目答案无法保证正确性，目前正在进行挑战答题，当通关后会更正所有错误答案并发布哈。

**Comment by mondayfirst** [comment]
@Tq7 
题库已经更新！于20220917，共答对4202道题，全部通关!
