### ISSUE TITLE
挑战答题报错，求助

### ISSUE THREAD

**Issue by ChengZhouzheng** [mondayfirst/XXQG_TiKu#22]
09:31:36.966/E: TypeError: Cannot read property "x" from null (/storage/emulated/0/脚本/建立题库_autoJS.js#169)
TypeError: Cannot read property "x" from null
    at find_true_answer_from_img (/storage/emulated/0/脚本/建立题库_autoJS.js:169:0)
    at /storage/emulated/0/脚本/建立题库_autoJS.js:69:0

**Comment by mondayfirst** [comment]
新版学习强国APP答题页面无法截屏，导致找不到正确答案坐标点。可使用老版本的学习强国来答题（比如2.33版本）

**Comment by mondayfirst** [comment]
@ChengZhouzheng 目前新版也已经可用了。因采用试对法，获取正确答案的速度较慢
