### ISSUE TITLE
建立题库，无法使用了吗？

### ISSUE THREAD

**Issue by 01buluo** [mondayfirst/XXQG_TiKu#25]
运行建立题库，无法识别题目啦，没显示，卡在题目那里

**Comment by mondayfirst** [comment]
我这里一切正常。更新脚本？更改脚本参数?软件无障碍或其它权限设置？

**Comment by 01buluo** [comment]
白天可以用了，昨晚半夜左右用不了

**Comment by 01buluo** [comment]
现在又没反应啦，卡在那里，是服务器的问题？本地下载的地址不能用，相对地址用不了，绝对地址又难找到
有什么方法吗?

**Comment by 01buluo** [comment]
好的，谢谢，另外请问一下，QG的挑战答题 选项顺序每次题目顺序是随机的吗？怎么和排序版的题库不一样呢？

**Comment by mondayfirst** [comment]
@01buluo 
现在选项是随机的。排序版的题库是把题目排序后保存的，通过这种方式来去除重复题目（仅选项顺序不同）。

**Comment by 01buluo** [comment]
哦，难怪呢，每次看到日志和答案不是一个顺序还以为哪里出问题呢，另外大佬，服务器那个题库常时不时连不上线，能否增加个直接调取这个平台你这个题库排序的文件选项，（手机本地地址那个不同手机相对地址和绝对地址不同，我荣耀手机用隐私模式账号，需要绝对地址，可是正常模式相对地址和绝对地址都没找到哪个能用，不知道是不是手机设置有问题），请大佬增加一个新的选择方式！

**Comment by mondayfirst** [comment]
App给予读取存储和网络权限，运行以下代码下载题库到同一目录下。
```
importClass(android.net.ConnectivityManager);
var cm = context.getSystemService(context.CONNECTIVITY_SERVICE);
var net = cm.getActiveNetworkInfo();
if (net == null || !net.isAvailable()) {
    toastLog("网络连接不可用!");
} else {
    toast("正在下载文件");
    var res_script = http.get("https://raw.githubusercontent.com/mondayfirst/XXQG_TiKu/main/%E9%A2%98%E5%BA%93_%E6%8E%92%E5%BA%8F%E7%89%88.json")
    if (res_script.statusCode == 200) {
        toastLog("题库下载成功");
        var jscontent = res_script.body.string();
        files.write("题库排序版.json", jscontent);
    }
    else{
        toastLog("下载失败，检查网络连接！")
    }
}
```

**Comment by 01buluo** [comment]
谢谢大佬，牛！

**Comment by 01buluo** [comment]
下载成功，但是过一会跳出来
20:21:25.125/E: Wrapped com.stardust.pio.UncheckedIOException: java.io.FileNotFoundException: /storage/emulated/0/脚本/题库排序版.json: open failed: ENOENT (No such file or directory) (6332e5d2f18afd599a3cd837.js#17)
Wrapped com.stardust.pio.UncheckedIOException: java.io.FileNotFoundException: /storage/emulated/0/脚本/题库排序版.json: open failed: ENOENT (No such file or directory)
    at 6332e5d2f18afd599a3cd837.js:17:0
请问大佬这是为什么呢？

**Comment by mondayfirst** [comment]
No such file or directory，没有这个文件或文件夹。
一、，解决文件夹是否存在的问题。检查这个文件夹路径是否存在，去存储目录看看有没有叫脚本的文件夹，autojs安装的时候默认脚本都在这个文件夹里。
二、解决文件是否存在的问题，就是检查你的Autojs是否有读写存储文件权限。
```
files.write("test.json", "123456");
```
测试一下，这行代码要是不报错，你读写权限就是有了，否则就是没有读写权限，得在应用权限里手动设置给软件权限，查询一下。
三、看情况大概率是设置的问题。如果以上都不行，说明你软件无法读写文件，建议换个版本试一试，因为旧手机无论使用之前的EMUI系统还是现在的HarmonyOS系统都是可以正常执行的。

对于缓存，在不依靠服务器的情况下，更新题库的时候必须要提取出题库文件来更新，放到缓存里最后也要保存到本地文件，都需要本地存储权限，因此我是直接一步到位保存到本地文件里，省事。等到有需要时再说吧，或者你针对这个问题pull request，锻炼锻炼，开源不就是让大家都来写嘛。

**Comment by 01buluo** [comment]
返回答案值出问题。技术不行还请帮忙查看查看

**Comment by 01buluo** [comment]
var host = "https://mondayfirst.top/tiku/" // 网络题库URL路径
这个网络题库服务好像一直不稳定，时不时连不上
有备选网址或者GitHub上的题库呢

**Comment by 01buluo** [comment]
host = "https://mondayfirst.top/tiku/" 
服务器时不时连不上，而且那个挑战答题索引 = "000001000000000000002010"也反馈为FALSE
,有什么方法吗？比如服务器不通直接跳出，干等着屏幕没有提示，然后报错

**Comment by mondayfirst** [comment]
> host = "https://mondayfirst.top/tiku/"
服务器时不时连不上，而且那个挑战答题索引 = "000001000000000000002010"也反馈为FALSE
,有什么方法吗？比如服务器不通直接跳出，干等着屏幕没有提示，然后报错

服务器最近没有任何变动，可能你网络问题，修改脚本后这回不直接报错了，等待至有连接就可。

**Comment by mondayfirst** [comment]
一般都有读取本地文件的权限啊，文件权限还没有的话，可能是软件或安装包问题
[Auto.js](https://raw.githubusercontent.com/dundunnp/auto_xuexiqiangguo/main/version-15.6/%E5%AE%89%E8%A3%85%E5%8C%85/autojsv4.1.1alpha2_downcc.com.apk)

**Comment by 01buluo** [comment]
谢谢，增加错等待，
我这边卡住是，一直在这个循环
while (true) {
    // 获取根节点
    globalIsObjFrame = false
    if (!className("android.widget.Image").depth(26).textMatches(/\S+/).exists()) {
        sleep(100)
        var obj_node = get_ui_obj_from_posstr(挑战答题索引)
        if (obj_node == null) {
            sleep(random_time(1000))
            continue
        }
请问是什么问题呢？或者能否超过一次数的循环后自动跳出循环呢？谢谢

**Comment by 01buluo** [comment]
后面就一直没有往下运行，循环上面的步骤

**Comment by 01buluo** [comment]
obj_node 为null，

**Comment by mondayfirst** [comment]
>obj_node 为null，

obj_node为null说明没有找到该控件，可能控件布局发生了变化，我所使用的APP版本正常运行啊，你的APP使用版本是啥啊。
> 请问是什么问题呢？或者能否超过一次数的循环后自动跳出循环呢？谢谢

如果超过一定次数的循环后自动跳出循环，脚本就会直接退出，程序运行结束。

**Comment by 01buluo** [comment]
版本2.38，有时又能用，有时就为null卡在那里
超过一定循环，比如多次为null时跳出循环
谢谢

**Comment by 01buluo** [comment]
[json2db.js](https://github.com/mondayfirst/XXQG_TiKu/blob/main/scripts/json2db.js)
13号添加的db，运行出错，是哪里需要设置或配置吗？谢谢
10:50:57.634/E: Wrapped android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (Sqlite code 14 SQLITE_CANTOPEN): Could not open database, (OS error - 2:No such file or directory) (6348ccebeb143e164c3814e6.js#11)
Wrapped android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (Sqlite code 14 SQLITE_CANTOPEN): Could not open database, (OS error - 2:No such file or directory)
    at 6348ccebeb143e164c3814e6.js:11:0

**Comment by mondayfirst** [comment]
@01buluo Auto.js没有存储读写权限，创建tiku.db文件失败，数据无法写入db文件，因此报错
啊，我十分怀疑你这个Auto.js版本或者权限设置有问题。😂你可以试试换个版本或加个权限，上面的问题可能都解决了。
毕竟手上就有华为手机，无论是EMUI系统还是现在的HarmonyOS系统，我在的autojs都是可以设置存储权限并在当前目录下创建文件的

**Comment by 01buluo** [comment]
哦哦，我用的是Hamibot，权限都开啦，是不适配这个吗？谢谢

**Comment by 01buluo** [comment]
对了，这个tiku.db是做什么用的呢？

**Comment by mondayfirst** [comment]
换成auto.js吧。我没用过hamibot，一知半解，猜测，可能为了保护商城脚本安全性，就不允许写操作？

**Comment by 01buluo** [comment]
大佬，今天一直报网络连接不通，是服务器哪里无法连接了吗？

**Comment by mondayfirst** [comment]
@01buluo 阿里云服务器部分机房发生故障，暂停提供相关服务。目前正在紧急维修中。
