### ISSUE TITLE
请教手动添加进去的题库，软件测试不能通过。

### ISSUE THREAD

**Issue by sntyuxi** [mondayfirst/XXQG_TiKu#26]
我按照题库规范要求       “  标题 。 |答案1 |答案2”：“正确答案”  手工添加的，软件测试就通过不了，不知为何。

{
"“一城十二泉”说的是        。来源：参见《中国国家人文地理》（中国地图出版社2019年版）|湖北咸宁|福建泉州": "湖北咸宁",
"黑龙江省伊春市的市树是        。来源：参见《中国国家人文地理》（中国地图出版社2019年版）|红松|黑松": "红松",
"辽宁        是我国煤精、琥珀的主要产地，拥有着悠久精湛的煤精琥珀雕刻加工技艺传承，是享誉世界的“乌金墨玉之都”。来源：参见《中国国家人文地理》（中国地图出版社2019年版）|抚顺|鞍山": "抚顺"
}

**Comment by sntyuxi** [comment]
Error:未找到正确答案！截屏失效(手动更改隐私模式参数)或颜色错误
    at find_true_answer_from_img ([remote]建立题库_autoJS_2.js:312:0)
    at click_answer_radio_button ([remote]建立题库_autoJS_2.js:157:0)
    at [remote]建立题库_autoJS_2.js:91:0

**Comment by sntyuxi** [comment]
大神： 我发现自己手工添加进去的答案1 答案2 的位置顺序都不能错，一错就报警，而且题干“英文引号内”必须全部一致（包括标点符号）不然也会报错。能否增加一个判断，达到90%就算对。
2 手工添加格式是否如右-->   “题干。|答案1|答案2”， “正确答案”
（英文双引号左+题干+句号+|答案1+|答案2+英文双引号右+英文逗号+空格+英文双引号左+正确答案+英文双引号右）

**Comment by mondayfirst** [comment]
注意：
1. 无障碍服务获取到的文本，在软件答案位置处是一种特殊的UTF8字符。在学习强国APP内以下划线显示，但在json中表现为显示为空白！不当的粘贴方式会将该字符转为空格字符，目前在答题时将不会被识别到该题目及答案。

2. 关于答案顺序的问题，答案是先经过排序，然后保存到题库的。在查询时，也会先排序答案，再从题库查找该题目及答案。因此，答案顺序必须相同。

3. 如果改为达到90%就算对，即通过模糊匹配查找答案。但json是字典，哈希表，不支持模糊查找。想使用模糊匹配需要将题库改为数据库，但没必要，APP内题目唯一，现在的方式能够点击并获取所有题目的正确答案。

这个项目的目的是通过自动化的方式获取APP上尽可能完整的正确题库，不信任手动添加的题目的正确性，遗漏的题目只要刷通挑战答题题库就会被更新。因为人为手动添加的题目的正确性存疑，可能污染题库，所以最初编写时就不支持手动添加哈。

**Comment by sntyuxi** [comment]
谢谢您的说明情况



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 下午4:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mondayfirst/XXQG_TiKu] 请教手动添加进去的题库，软件测试不能通过。 (Issue #26)





 
注意：
  
 
无障碍服务获取到的文本，在软件答案位置处是一种特殊的UTF8字符。在学习强国APP内以下划线显示，但在json中表现为显示为空白！不当的粘贴方式会将该字符转为空格字符，目前在答题时将不会被识别到该题目及答案。
 
 
 
关于答案顺序的问题，答案是先经过排序，然后保存到题库的。在查询时，也会先排序答案，再从题库查找该题目及答案。因此，答案顺序必须相同。
 
 
 
如果改为达到90%就算对，即通过模糊匹配查找答案。但json是字典，哈希表，不支持模糊查找。想使用模糊匹配需要将题库改为数据库，但没必要，APP内题目唯一，现在的方式能够点击并获取所有题目的正确答案。
 
  
这个项目的目的是通过自动化的方式获取APP上尽可能完整的正确题库，不信任手动添加的题目的正确性，遗漏的题目只要刷通挑战答题题库就会被更新。因为人为手动添加的题目的正确性存疑，可能污染题库，所以最初编写时就不支持手动添加哈。
