### ISSUE TITLE
题库能不能取消：“来源：XXXXXX”

### ISSUE THREAD

**Issue by sntyuxi** [mondayfirst/XXQG_TiKu#27]
在答题是否能取消“来源：xxx”的判断条件？

**Comment by wangwang-code** [comment]
> 因为题库是json，字典，哈希表，只支持完全匹配。在查找时取消来源字样，就需要题库里取消来源字样。如果这样做，就先需要重建一个没有来源字样的题库，在答题时相当于从原本的单线变成两条并行分支，比较麻烦，感觉不是普遍需求，目前不会修改它。

可以将json转换成两个数组，一个题目一个答案
然后用双重for循环 将所有题 逐个字匹配算出匹配度 选取匹配的最高的题目的下标 
用下标找到对应的答案

**Comment by mondayfirst** [comment]
> 
> > 因为题库是json，字典，哈希表，只支持完全匹配。在查找时取消来源字样，就需要题库里取消来源字样。如果这样做，就先需要重建一个没有来源字样的题库，在答题时相当于从原本的单线变成两条并行分支，比较麻烦，感觉不是普遍需求，目前不会修改它。
> 
> 可以将json转换成两个数组，一个题目一个答案 然后用双重for循环 将所有题 逐个字匹配算出匹配度 选取匹配的最高的题目的下标 用下标找到对应的答案

一般性：一个问题逐字与另一个问题的文本进行匹配度计算，双重for循环，复杂度是O(n<sup>2</sup>)，使用哈希表，复杂度是O(n)。进而，一个问题与所有问题的匹配度计算是O(n<sup>2</sup>)或O(n<sup>3</sup>)。如果一个问题平均长度是20个字符，5000个题目全部计算，依照上面的计算方法，在哈希表下的最多计算量是20*5000=100000(为方便理解的直观表示，实际不是)。

个性化：而分成两个题库并行查询，字典匹配为哈希表，哈希表是O(1)的复杂度，在哈希表下的最多计算量是1+1=2(为方便理解的直观表示，实际不是)

在SQL数据库里，如果问题的文本里的文字全都是无错的，可以通过正则表达式匹配。

举例：
问题是: 中国。
SQL语句(类似语句，没有实际测试)：
```
SELECT question 
FROM data  
WHERE question REGEXP '([^中国]*)([中国][^中国]*){2,50}([^中国]*)'
```
每个括号内为一组
([^中国]*) 表示匹配非“中”和“国”的单个字符0次到多次

([中国][^中国]*){2,50}表示匹配，第一个字符为“中”或“国”的单个字符以及之后的非中国字符0次到多次，整组必须出现2次(中国是两个字符，因此该组至少出现两次)到50次(设置的最大出现次数)

对于以下文本，该表达式应该都能识别出来：
>中3中
中国中
国*中
3国3456中3
3国2中5国3中2

由于是C++编写的函数，经过优化编译，速度上应当比自己写JS调要快，尽管正则匹配对应规则的过程中可能计算量更大。

**Comment by wangwang-code** [comment]
> 如果问题的文本里的文字全都是无错的，可以通过正则表达式匹配。

很遗憾，受OCR限制，这一点无法100%做到

**Comment by wangwang-code** [comment]
> 双重for循环，复杂度是O(n2)，使用哈希表，复杂度是O(n)。进而，一个问题与所有问题的匹配度计算是O(n2)或O(n3)。

实际上并非全部需要进行匹配，相识度很高完全可以跳出循环
虽然OCR的准确性感人，但前两个字还是准的，完全可以先用两字过滤一边题库的

在实际使用上
天机800
可以在0.8秒左右对题库所有题进行相识度计算

**Comment by mondayfirst** [comment]
基于当前的电脑环境，这是一个python脚本示例，用javascript是一样的效果。
```
import re
import json

data = {
    "由延安鲁迅艺术学院的艺术家们集体创作的中国第一部新歌剧        ，通过真实而富有传奇色彩的故事，揭示了“旧社会把人逼成‘鬼’，新社会把‘鬼’变成人”这一鲜明的时代主题，对宣传教育根据地军民起到重要作用。来源：参见《中国共产党宣传工作简史》（人民出版社2022年版）|《保卫家乡》|《白毛女》":
    "《白毛女》",
    "1927年1月4日至2月5日，毛泽东到湖南的湘潭、湘乡等县考察农民运动，写成        。他在报告中指出：“很简单的一些标语、图画和讲演，使得农民如同每个都进过一下子政治学校一样，收效非常之广而速。”来源：参见《中国共产党宣传工作简史》（人民出版社2022年版）|《寻乌调查》|《湖南农民运动考察报告》":
    "《湖南农民运动考察报告》",
    "东汉末年，帝室大乱，        胁迫朝臣同意废除少帝刘辩，扶立董太后之孙刘协为汉献帝。来源：参见《中国军事通史》（军事科学出版社1998年版）|董卓|董旻":
    "董卓",
    "《史记》包括十二本纪、十表、八书、三十世家、七十列传，共130篇。其中，主要记载历代帝王世系及军国大事的体裁是        。来源：参见中国社会科学词条库|世家|列传|本纪|表":
    "本纪",
    "2019年8月22日，习近平在甘肃考察工作结束时指出：“我2009年来甘肃的时候，总结其为‘两点一存’，就是        为党中央和各路长征红军提供了落脚点，为后来八路军主力奔赴抗日前线提供了出发点，成为土地革命战争后期全国硕果仅存的完整革命根据地。”来源：《论中国共产党历史》（中央文献出版社2021年版）|鄂豫皖革命根据地|陕甘革命根据地":
    "陕甘革命根据地",
    "作为武器化生物战剂，炭疽杆菌致病力较强，在无防护条件下，呼吸        可引起人群50%发生吸入性炭疽病。来源：《国防科技奥秘》（山东科学技术出版社2013年版）|1分钟|1小时":
    "1分钟",
    "南宋末年，忽必烈率领蒙军攻打南宋，这场战役史称        ，也是蒙古灭南宋的关键一战。来源：参见《改变历史的二十四场战争》（中华书局2017年版）|襄樊之战|郾（yǎn）城之战":
    "襄樊之战",
    "现代战争要求兵器系统具有良好的隐身技术。隐身技术的应用可使兵器装备的雷达反射截面积比同类非隐身装备        。来源：参见《兵器概论》（国防工业出版社2008年版）|大|小":
    "小",
    "公元588年年底至589年年初，隋文帝以晋王        为统帅，兵分八路，南下平陈。隋灭陈统一全国，结束了长期的分裂局面，翻开了历史的新篇章，影响深远。来源：参见《改变历史的二十四场战争》（中华书局2017年版）|杨侑|杨广":
    "杨广",
    "宋代民族英雄岳飞从丰富的实践经验中总结出：“勇不足恃，用兵在先定        。”来源：参见《古代军旅常识》（军事科学出版社1991年版）|将|谋":
    "谋",
    "障碍类器械是古代战争中用于阻止和迟滞敌方行动的器械，尤其对于        具有一定的杀伤效能。来源：《图说中国古代兵器与兵书》（世界图书出版西安公司2007年版）|弓箭手|步兵|骑兵":
    "骑兵",
    "发生在唐武德年间的        ，是李唐实现全国统一的关键之战，同时也是一个围城打援的经典战例。来源：参见《改变历史的二十四场战争》（中华书局2017年版）|童山之战|虎牢关之战":
    "虎牢关之战",
}
query_str = "中国共产党"
pattern_str = "(\"[^" + query_str + "\"]*(?:[" + query_str + "][^" + query_str + "\"]*){" + str(len(query_str)) + ",1000}[^\"]*\")"
res = re.findall(pattern_str, json.dumps(data, ensure_ascii=False))

print("匹配到的个数：", len(res))
for i in res:
    print(i)
```
输出内容为：
```
匹配到的个数： 4
"由延安鲁迅艺术学院的艺术家们集体创作的中国第一部新歌剧        ，通过真实而富有传奇色彩的故事，揭示了“旧社会把人逼成‘鬼’，新社会把‘鬼’变成人”这一鲜明的时代主题，对宣传教育根据地军民起到重要作用。来源：参见《中国共产党宣传工作简史》（人民出版社2022年版）|《保卫家乡》|《白毛女》"
"1927年1月4日至2月5日，毛泽东到湖南的湘潭、湘乡等县考察农民运动，写成        。他在报告中指出：“很简单的一些标语、图画和讲演，使得农民如同每个都进过一下子政治学校一样，收效非常之广而速。”来源：参见《中国共产党宣传工作简史》（人民出版社2022年版）|《寻乌调查》|《湖南农民运动考察报告》"
"《史记》包括十二本纪、十表、八书、三十世家、七十列传，共130篇。其中，主要记载历代帝王世系及军国大事的体裁是        。来源：参见中国社会科学词条库|世家|列传|本纪|表"
"2019年8月22日，习近平在甘肃考察工作结束时指出：“我2009年来甘肃的时候，总结其为‘两点一存’，就是        为党中央和各路长征红军提供了落脚点，为后来八路军主力奔赴抗日前线提供了出发点，成为土地革命战争后期全国硕果仅存的完整革命根据地。”来源：《论中国共产党历史》（中央文献出版社2021年版）|鄂豫皖革命根据地|陕甘革命根据地"
```

对于这一道题目来说，期望的“中国共产党”字符并没有全部匹配到并出现(中2，国2，共1，产0，党0)，即使文本有错误，也不影响匹配结果，非常适合OCR容错。并且这种匹配使用内置函数，非常快，而且规则简单，算法复杂度低，基本上一次遍历题库即可匹配出所有符合的题目。
>"《史记》包括十二本纪、十表、八书、三十世家、七十列传，共130篇。其中，主要记载历代帝王世系及军国大事的体裁是        。来源：参见中国社会科学词条库|世家|列传|本纪|表"

事实上，构造更长的表达式，或者进行二次匹配，可以只保留“中国共产党”全部出现的题目。基于这样的结果进行文本相似度计算也会更快。

**Comment by wangwang-code** [comment]
> 基于当前的电脑环境，这是一个python脚本示例，用javascript是一样的效果。
> 
> ```
> import re
> import json
> 
> data = {
>     "由延安鲁迅艺术学院的艺术家们集体创作的中国第一部新歌剧        ，通过真实而富有传奇色彩的故事，揭示了“旧社会把人逼成‘鬼’，新社会把‘鬼’变成人”这一鲜明的时代主题，对宣传教育根据地军民起到重要作用。来源：参见《中国共产党宣传工作简史》（人民出版社2022年版）|《保卫家乡》|《白毛女》":
>     "《白毛女》",
>     "1927年1月4日至2月5日，毛泽东到湖南的湘潭、湘乡等县考察农民运动，写成        。他在报告中指出：“很简单的一些标语、图画和讲演，使得农民如同每个都进过一下子政治学校一样，收效非常之广而速。”来源：参见《中国共产党宣传工作简史》（人民出版社2022年版）|《寻乌调查》|《湖南农民运动考察报告》":
>     "《湖南农民运动考察报告》",
>     "东汉末年，帝室大乱，        胁迫朝臣同意废除少帝刘辩，扶立董太后之孙刘协为汉献帝。来源：参见《中国军事通史》（军事科学出版社1998年版）|董卓|董旻":
>     "董卓",
>     "《史记》包括十二本纪、十表、八书、三十世家、七十列传，共130篇。其中，主要记载历代帝王世系及军国大事的体裁是        。来源：参见中国社会科学词条库|世家|列传|本纪|表":
>     "本纪",
>     "2019年8月22日，习近平在甘肃考察工作结束时指出：“我2009年来甘肃的时候，总结其为‘两点一存’，就是        为党中央和各路长征红军提供了落脚点，为后来八路军主力奔赴抗日前线提供了出发点，成为土地革命战争后期全国硕果仅存的完整革命根据地。”来源：《论中国共产党历史》（中央文献出版社2021年版）|鄂豫皖革命根据地|陕甘革命根据地":
>     "陕甘革命根据地",
>     "作为武器化生物战剂，炭疽杆菌致病力较强，在无防护条件下，呼吸        可引起人群50%发生吸入性炭疽病。来源：《国防科技奥秘》（山东科学技术出版社2013年版）|1分钟|1小时":
>     "1分钟",
>     "南宋末年，忽必烈率领蒙军攻打南宋，这场战役史称        ，也是蒙古灭南宋的关键一战。来源：参见《改变历史的二十四场战争》（中华书局2017年版）|襄樊之战|郾（yǎn）城之战":
>     "襄樊之战",
>     "现代战争要求兵器系统具有良好的隐身技术。隐身技术的应用可使兵器装备的雷达反射截面积比同类非隐身装备        。来源：参见《兵器概论》（国防工业出版社2008年版）|大|小":
>     "小",
>     "公元588年年底至589年年初，隋文帝以晋王        为统帅，兵分八路，南下平陈。隋灭陈统一全国，结束了长期的分裂局面，翻开了历史的新篇章，影响深远。来源：参见《改变历史的二十四场战争》（中华书局2017年版）|杨侑|杨广":
>     "杨广",
>     "宋代民族英雄岳飞从丰富的实践经验中总结出：“勇不足恃，用兵在先定        。”来源：参见《古代军旅常识》（军事科学出版社1991年版）|将|谋":
>     "谋",
>     "障碍类器械是古代战争中用于阻止和迟滞敌方行动的器械，尤其对于        具有一定的杀伤效能。来源：《图说中国古代兵器与兵书》（世界图书出版西安公司2007年版）|弓箭手|步兵|骑兵":
>     "骑兵",
>     "发生在唐武德年间的        ，是李唐实现全国统一的关键之战，同时也是一个围城打援的经典战例。来源：参见《改变历史的二十四场战争》（中华书局2017年版）|童山之战|虎牢关之战":
>     "虎牢关之战",
> }
> query_str = "中国共产党"
> pattern_str = "(\"[^" + query_str + "\"]*(?:[" + query_str + "][^" + query_str + "\"]*){" + str(len(query_str)) + ",1000}[^\"]*\")"
> res = re.findall(pattern_str, json.dumps(data, ensure_ascii=False))
> 
> print("匹配到的个数：", len(res))
> for i in res:
>     print(i)
> ```
> 
> 输出内容为：
> 
> ```
> 匹配到的个数： 4
> "由延安鲁迅艺术学院的艺术家们集体创作的中国第一部新歌剧        ，通过真实而富有传奇色彩的故事，揭示了“旧社会把人逼成‘鬼’，新社会把‘鬼’变成人”这一鲜明的时代主题，对宣传教育根据地军民起到重要作用。来源：参见《中国共产党宣传工作简史》（人民出版社2022年版）|《保卫家乡》|《白毛女》"
> "1927年1月4日至2月5日，毛泽东到湖南的湘潭、湘乡等县考察农民运动，写成        。他在报告中指出：“很简单的一些标语、图画和讲演，使得农民如同每个都进过一下子政治学校一样，收效非常之广而速。”来源：参见《中国共产党宣传工作简史》（人民出版社2022年版）|《寻乌调查》|《湖南农民运动考察报告》"
> "《史记》包括十二本纪、十表、八书、三十世家、七十列传，共130篇。其中，主要记载历代帝王世系及军国大事的体裁是        。来源：参见中国社会科学词条库|世家|列传|本纪|表"
> "2019年8月22日，习近平在甘肃考察工作结束时指出：“我2009年来甘肃的时候，总结其为‘两点一存’，就是        为党中央和各路长征红军提供了落脚点，为后来八路军主力奔赴抗日前线提供了出发点，成为土地革命战争后期全国硕果仅存的完整革命根据地。”来源：《论中国共产党历史》（中央文献出版社2021年版）|鄂豫皖革命根据地|陕甘革命根据地"
> ```
> 
> 对于这一道题目来说，期望的“中国共产党”字符并没有全部匹配到并出现(中2，国2，共1，产0，党0)，即使文本有错误，也不影响匹配结果，非常适合OCR容错。并且这种匹配使用内置函数，非常快，而且规则简单，算法复杂度低，基本上一次遍历题库即可匹配出所有符合的题目。
> 
> > "《史记》包括十二本纪、十表、八书、三十世家、七十列传，共130篇。其中，主要记载历代帝王世系及军国大事的体裁是        。来源：参见中国社会科学词条库|世家|列传|本纪|表"
> 
> 事实上，构造更长的表达式，或者进行二次匹配，可以只保留“中国共产党”全部出现的题目。基于这样的结果进行文本相似度计算也会更快。

这种非常适合对题库的初筛，但现在已经使用上面的方案，即使用前两字进行初筛，目前耗时已经低于0.5秒 (天机800) 非常可观 最低4ms

**Comment by mmtou** [comment]
取消来源是定制化需求，可以自己单独处理下；有的人是需要来源的，比如说我

**Comment by PutinYpa** [comment]
> 
用数据库的方式可以更灵活，使用select answer from tiku where question like '%keyword1%keyword2%keyword3'
