### ISSUE TITLE
如何转换为db的版本？

### ISSUE THREAD

**Issue by lukemin** [Mondayfirst/XXQG_TiKu#3]
如何转换为db的版本？

**Comment by Mondayfirst** [comment]
db里的数据存储具体格式是什么呢？转为db后里面数据的列名不一样也没法用

**Comment by lukemin** [comment]
https://github.com/auto-xxqg/xxqg_tiku_online

**Comment by Mondayfirst** [comment]
> 打开db文件参考链接：https://jingyan.baidu.com/article/597a06430b5ade312b5243c1.html
> db文件导入csv参考链接：https://jingyan.baidu.com/article/59a015e375b25af795886558.html

步骤：
1. 转换json为db里的存储格式，csv、json、xlsx都可以，生成question和answer字段，注意在question字段删除“|”符号后的答案，并将问题中原本下划线位置的空格删去。
2. 参考给出的打开文件链接打开题库，选择导入，参考导入链接导入数据，并保存。

**Comment by Mondayfirst** [comment]
而且你给的仓库里的代码中有插入sqlite的示例，在python里安装sqlite3包，读取本仓库里的json稍微改改再往db里插入一下数据就好了
你给的仓库里的部分插入代码：（摘了一部分，详情看他的的源代码）
tiku.py 17行 `g.db = sqlite3.connect(DATABASE)`
tiku.py 26-46行 `def execute(sql, param=None) ...`
tiku.py 97行 `execute(f'insert into {tableName}(question,answer,datetime) values (?,?,?)', (question, answer, t))`

**Comment by Mondayfirst** [comment]
去https://github.com/auto-xxqg/xxqg_tiku_online里面的Telegram群组问吧，那个库的作者已经写了js脚本。
