### ISSUE TITLE
老大，QG版本强制升级啦，

### ISSUE THREAD

**Issue by 01buluo** [mondayfirst/XXQG_TiKu#30]
如题，强制升级，如何破解？谢谢

**Comment by fdq236** [comment]
您好，我已收到您发的邮件！待我看后回复！谢谢啦！
                                                                      pcq泉

**Comment by mondayfirst** [comment]
@01buluo 
1. 应用市场设置更新白名单
2. 或者使用更高一点的旧版本

**Comment by 01buluo** [comment]
更高的旧版本也要求升级……，点击就弹窗，无法点击……有什么办法吗？xp框架或者去除强制弹出
谢谢

**Comment by mondayfirst** [comment]
@01buluo 不去root或者破解没啥办法。没事，新版也能刷，就是获取正确答案慢了点。
