### ISSUE TITLE
想修改成手动点击，请教一下大神

### ISSUE THREAD

**Issue by seaser-i** [mondayfirst/XXQG_TiKu#31]
如题，在使用了大神的代码后发现很好用，但是一些原因，想增加一个悬浮窗显示题目的答案，并把自动点击改成人工点击（方便有时候背题），作为小白尝试过增加console.show()和修改后面的click。发现还是会自动点击，希望大神能指点一下

**Comment by mondayfirst** [comment]
> 如题，在使用了大神的代码后发现很好用，但是一些原因，想增加一个悬浮窗显示题目的答案，并把自动点击改成人工点击（方便有时候背题），作为小白尝试过增加console.show()和修改后面的click。发现还是会自动点击，希望大神能指点一下


1. 下面的函数的函数体设为空。
https://github.com/mondayfirst/XXQG_TiKu/blob/490bc707bebef9bd920ec9bfd8f6125478240839/%E5%BB%BA%E7%AB%8B%E9%A2%98%E5%BA%93_autoJS.js#L141-L161
```function click_answer_radio_button(answer_uis, question, answers, idx, isMustPost, obj_node) {}```

2. 显示控制台，一开始加上
```console.show();``` 

3. 这个函数体内加入显示正确答案的代码
https://github.com/mondayfirst/XXQG_TiKu/blob/490bc707bebef9bd920ec9bfd8f6125478240839/%E5%BB%BA%E7%AB%8B%E9%A2%98%E5%BA%93_autoJS.js#L86-L88
```console.clear();```
```console.log(answers[true_answer_index]);```
