### ISSUE TITLE
这个下载了怎么用，大神指导一下

### ISSUE THREAD

**Issue by wwsoo** [mondayfirst/XXQG_TiKu#32]
小白一个，下载后，不知道怎么使用，求帮助

**Comment by mondayfirst** [comment]
需要题库的看json和md文件
需要脚本的单单使用建立题库js脚本，在挑战答题界面通过autojs运行
需要自建服务端程序的参考其它

**Comment by yangchaohe** [comment]
> 

请问autojs的版本是？

**Comment by yangchaohe** [comment]
> 需要题库的看json和md文件 需要脚本的单单使用建立题库js脚本，在挑战答题界面通过autojs运行 需要自建服务端程序的参考其它

请问autojs的版本是？

**Comment by mondayfirst** [comment]
> > 需要题库的看json和md文件 需要脚本的单单使用建立题库js脚本，在挑战答题界面通过autojs运行 需要自建服务端程序的参考其它
> 
> 请问autojs的版本是？

Autojs现在有对应用程序的限制，部分App无法使用。找之前的开源的版本，网上挺多的4.1等版本。autoxjs也可以。

**Comment by mondayfirst** [comment]
重要的不是题库吗，一般背背题就好了吧。要是想刷分的，可以去别的仓库看看

**Comment by mondayfirst** [comment]
对于大部分人来说，获取markdown文件的题库从头到尾背一遍就足够了。
对于部分需要题库来实现其它开发需求的，使用json文件的题库即可，转成数据库格式也行。

要是希望
1. 自己建立个人题库
2. 为服务器更新题库
3. 截图挑战通关字样
4. 简单的挑战下自己的动手能力

可以使用js脚本完成挑战答题。
自建服务端更麻烦些，推荐有基础且有需要的自行实现。

还望大家专注于题目本身，好好学习，天天向上！
