### ISSUE TITLE
大神，这个题库可以作为四人、每日、双人，专项题库吗？谢谢

### ISSUE THREAD

**Issue by 01buluo** [mondayfirst/XXQG_TiKu#33]
大神，这个题库可以作为四人、每日、双人，专项题库吗？谢谢

**Comment by mondayfirst** [comment]
四人和每日可以，差不多，专项不行

**Comment by 01buluo** [comment]
好的，谢谢

**Comment by 01buluo** [comment]
其它仓库题库没有你这个时时更新，感谢大神
另外，请教个问题，能否简单写个脚本，上传到这个github仓库文件或图片，比如生成图片或其它文本直接传到该仓库，万分感谢！

**Comment by mondayfirst** [comment]
@01buluo 没有开放这个权限，可通过Github的“Pull Requests”功能提交差异内容，然后我审核内容合并分支。你看看能不能满足你的想法吧。

**Comment by 01buluo** [comment]
谢谢大神，厉害！
我意思是我想自己建个Github仓，然后上传到自己的仓的脚本，请大神帮忙写个看，谢谢

**Comment by mondayfirst** [comment]
https://github.com/mondayfirst/XXQG_TiKu/blob/f7f731496001488589f9cd9306d2ddb5c4db271f/scripts/git_push.sh

可参考该文件的后三行，比较基础。
此外在搜索引擎查询“git的命令行运行”，有很多文章详细讲述，也有进阶内容。

**Comment by 01buluo** [comment]
嗯嗯，我研究研究，非常感谢
