### ISSUE TITLE
大神，那个三人航天有题库和自动答题吗?谢谢

### ISSUE THREAD

**Issue by 01buluo** [mondayfirst/XXQG_TiKu#34]
大神，那个三人航天有题库和自动答题吗?谢谢

**Comment by mondayfirst** [comment]
无，全新题库。答题过程和四人赛一样，text内容隐藏，需要root或OCR识别。
手上暂时没有ios系统的手机和平板，不然可以抓包看看https传输过程中是否使用二次加密。如果没有二次加密就可以获取题目。

**Comment by 01buluo** [comment]
好的，谢谢
