### ISSUE TITLE
mondayfirst/xxqgtiku-server 这个容器要如何使用？

### ISSUE THREAD

**Issue by zhangop9** [mondayfirst/XXQG_TiKu#35]
mondayfirst/xxqgtiku-server 这个容器要如何使用？

docker run --restart=always --name=xxqg-tiku -p 1880:1880 -v /volume1/docker/XXQG_TiKu/:/root/app/XXQG_TiKu -itd mondayfirst/xxqgtiku-server /bin/bash

可以启动，但是没法查题目。

**Comment by mondayfirst** [comment]
服务器端口1880，模式要改，ip地址要改。
https://github.com/mondayfirst/XXQG_TiKu/blob/415d441c3627d1e2f48e17e4540d80ec76479b1e/%E5%BB%BA%E7%AB%8B%E9%A2%98%E5%BA%93_autoJS.js#L8
https://github.com/mondayfirst/XXQG_TiKu/blob/415d441c3627d1e2f48e17e4540d80ec76479b1e/%E5%BB%BA%E7%AB%8B%E9%A2%98%E5%BA%93_autoJS.js#L10
本地端口就是
`var host = "http://127.0.0.1:1880"`

**Comment by zhangop9** [comment]
https://mondayfirst.top/tiku/
这个网址可以正常用，
var host = "http://127.0.0.1:1880"
docker版的不能正常用，也是拉的你的那个注册表
能不能写个部署的说明。

**Comment by zhangop9** [comment]
import requests

data = {"q": "扑救火灾最有利的阶段是        。|火灾初起阶段|火灾发展阶段|火灾猛烈燃烧阶段"}

# 正确访问
response = requests.post("https://mondayfirst.top/tiku/query", data)
print(response.status_code, response.text)

response = requests.post("http://172.18.63.244:1880", data)
print(response.status_code, response.text)

**Comment by mondayfirst** [comment]
```
git clone https://github.com/mondayfirst/XXQG_TiKu.git
docker pull mondayfirst/xxqgtiku-server:latest

# Set params
ContainerName = xxqg_tiku_server
ExternalPort = 1880
ExternalPath = $PWD/XXQG_TiKu
# Run
docker run --restart=always --name=${ContainerName} -p ${ExternalPort}:1880 -v ${ExternalPath}:/root/app/XXQG_TiKu -itd mondayfirst/xxqgtiku-server:latest /bin/bash /root/app/XXQG_TiKu/scripts/run_docker.sh
```

**Comment by zhangop9** [comment]
因此需要将题库文件等映射到容器内指定路径，这个不会做
容器可以运行

**Comment by mondayfirst** [comment]
```-v ${ExternalPath}:/root/app/XXQG_TiKu```
这部分实现映射路径，具体可查阅[Docker run 命令（菜鸟教程）](https://www.runoob.com/docker/docker-run-command.html)

**Comment by zhangop9** [comment]
-v /volume1/docker/XXQG_TiKu/:/root/app/XXQG_TiKu

**Comment by zhangop9** [comment]
将空的题库放有注册表中，我们下载后直接用就好了

**Comment by zhangop9** [comment]
放弃了，谢谢

**Comment by mondayfirst** [comment]
docker run --restart=always --name=xxqg-tiku -p 1880:1880 -v /volume1/docker/XXQG_TiKu/:/root/app/XXQG_TiKu -itd mondayfirst/xxqgtiku-server /bin/bash

最后的/bin/bash 后面得跟/root/app/XXQG_TiKu/scripts/run_docker.sh

容器CMD和ENTRYPOINT默认为bash，加上后面的脚本地址才会执行程序响应网络请求

**Comment by mondayfirst** [comment]
> 将空的题库放有注册表中，我们下载后直接用就好了

这个是个好方法，等有时间再说吧

**Comment by ThatCoders** [comment]
> 放弃了，谢谢

看到这我也就放弃了，极矣!
