### ISSUE TITLE
题库中部分有问题的数据

### ISSUE THREAD

**Issue by AllenKH** [mondayfirst/XXQG_TiKu#36]
"6亿吨，其中80%以上的贡献来自        。|人造林|天然林": "天然林"
**部分题干缺失**

"170元，晚上10点到早上6点每度仅为0.3070元，错峰用电的意义在于        。|仅仅只是为居民节约了电费|优化电力资源配置，提高电力供应整体的效率与效益|增加电网的峰谷负荷差|提倡工厂增加夜班排班量": "优化电力资源配置，提高电力供应整体的效率与效益"
**部分题干缺失**

"根据《中华人民共和国野生动物保护法》，国家重点保护的野生动物分为。|一级和二级保护野生动物|有科研价值和经济价值的野生动物|珍贵和濒危野生动物": "一级和二级保护野生动物"
**题干中缺少空格**

"根据《中华人民共和国证券法》，证券交易即时行情的权益由依法享有。|投资者|证券交易所|证券登记结算机构|证监会": "证券交易所"
**题干中缺少空格**

"劳动能力鉴定是指劳动功能障碍程度和生活自理障碍程度的等级鉴定。劳动功能障碍分为个伤残等级。|十|十一|十三|十二": "十"
**题干中缺少空格**

"《中华人民共和国国家安全法》规定，领导全国武装力量，决定军事战略和武装力量的作战方针，统一指挥维护国家安全的军事行动。|中央军事委员会|全国人民代表大会|全国人民代表大会常务委员会|国务院": "中央军事委员会"
**题干中缺少空格**

"根据《全国人口普查条例》，人口普查每年进行一次。|10|15|20|5": "10"
**题干中缺少空格**

 "开发利用水资源，应当首先满足用水。|农业|城乡居民生活|工业|生态环境": "城乡居民生活"
**题干中缺少空格**

"雕塑是具象的物体形成，以实空间为主，伴随着虚空间，是艺术。来源：《中国大百科全书》（第三版网络版）（中国大百科全书出版社）|平面|立体": "立体"
**题干中缺少空格**

"唐代诗人曾经夜宿小山楼，留下诗作《题金陵渡》:“金陵津渡小山楼，一宿行人自可愁，潮落夜江斜月里，两三星火是瓜洲。”|张祜|李白|杜牧|杜甫": "张祜"
**题干中缺少空格**

"中国对外援助从帮助开始起步。|亚非拉国家|发达国家|周边友好国家|最不发达国家": "周边友好国家"
**题干中缺少空格**

"张家界是张家界市永定区地方传统戏剧，“金线吊葫芦”的演唱方法是其典型艺术特征。|湘剧|花鼓戏|阳戏": "阳戏"
**题干中缺少空格**

"著作权又称版权，是对作者或其他著作权人依法对文学、艺术或科学作品所享有的各项专有权利的总称。来源：《中国大百科全书》（第三版网络版）（中国大百科全书出版社）|正确|错误": "正确"
**题干中缺少空格**

"选择词语的正确词形。|挑三拣四|挑三捡四": "挑三拣四"
**题干中缺少空格**

"歌曲《共产儿童团歌》出自于1958年长春电影制片厂出品的电影。|《上甘岭》|《祖国的花朵》|《红孩子》|《英雄儿女》": "《红孩子》"
**题干中缺少空格**

"为保护个人信息安全，不应当。|使用后及时销毁身份证复印件|及时撕毁快递包裹上的个人信息|输入密码时确保无人偷窥|随意“海投”个人简历": "随意“海投”个人简历"
**题干中缺少空格**

"位于福建省中西北部的市，是国务院批准建立的全国集体林区改革试验区，有单位面积产量居世界之冠的“宁化古杉木王群”。|三明|宁德|泉州|漳州": "三明"
**题干中缺少空格**

**Comment by mondayfirst** [comment]
缺失空格是因为部分新题目与旧题目之间只有空格的差异。为便于查询，将所有题目删除空格保存。
部分题干缺失也是类似的，有的题目和新题目间存在内容差异，就同时保留了新旧题目。
