### ISSUE TITLE
大佬，想请问下，格式转不知道能否帮忙修改下题库

### ISSUE THREAD

**Issue by 01buluo** [mondayfirst/XXQG_TiKu#37]
https://github.com/Pandaver/XXQG_TiKu_Transform
中[utils.js](https://github.com/Pandaver/XXQG_TiKu_Transform/blob/main/utils.js)转成question，把答案选项放在前面的（D 根据《中华人民共和国土壤污染防治法》，未达到土壤污染风险评估报告确定的风险管控、修复目标的建设用地地块，禁止开工建设任何与        无关的项目。 后期管理	效果评估	调查评估	风险管控、修复
A 最早的地理学著作        记录了我国古代地理、历史、民族、神话、生物、水利等诸多方面的内容。 《山海经》	《水经注》	《皇舆全览图》	《禹贡地域图》）
https://github.com/Pandaver/XXQG_TiKu_Transform/blob/main/question
直接运行老是报错，大佬能转换下吗？

**Comment by mondayfirst** [comment]
看起来代码是创建新的数据库并写入，可能还是程序权限的问题导致报错
