### ISSUE TITLE
怎么用啊 跟文本一样打开 查找吗？

### ISSUE THREAD

**Issue by sd252457109** [Mondayfirst/XXQG_TiKu#4]
怎么用啊 跟文本一样打开 查找吗？

**Comment by Mondayfirst** [comment]
程序：用后缀为“.json”的文件，根据固定的格式读取题目与答案
非程序：用后缀为“.md”的文件，在打开的网页中查找或在markdown相关软件的预览中查找

**Comment by rui03y** [comment]
>


> 程序：用后缀为“.json”的文件，根据固定的格式读取题目与答案 非程序：用后缀为“.md”的文件，在打开的网页中查找或在markdown相关软件的预览中查找

有什么可以搭配使用的软件吗

**Comment by Mondayfirst** [comment]
> > 
> 
> > 程序：用后缀为“.json”的文件，根据固定的格式读取题目与答案 非程序：用后缀为“.md”的文件，在打开的网页中查找或在markdown相关软件的预览中查找
> 
> 有什么可以搭配使用的软件吗

不提供我自己写的

隔壁也有，能导入json题库，你去瞅瞅： 
https://github.com/auto-xxqg/auto-xxqg
