### ISSUE TITLE
您好作者，我想请问如果自己加题目怎么加

### ISSUE THREAD

**Issue by xiaoleileng** [Mondayfirst/XXQG_TiKu#6]
您好作者，我想请问如果自己加题目怎么加，然后可不可以做成网络题库的形式

**Comment by Mondayfirst** [comment]
> 问: 我想请问如果自己加题目怎么加

答：下载json文件至本地，通过字典添加修改json文件

> 问: 可不可以做成网络题库的形式

答：可以，不难。做成网络题库后用户可通过API提交问题和答案来做到每日更新，但服务器费用是核心问题。

**Comment by Mondayfirst** [comment]
@xiaoleileng 已经做成网络题库的形式，你还想自己加题目吗？
