### ISSUE TITLE
您好，题库好像不全，是不是没有完整答完题目，谢谢

### ISSUE THREAD

**Issue by git898989** [mondayfirst/XXQG_TiKu#9]

**Comment by dang1013** [comment]
作者的题库是我见过最全的了，你是怎么发现它不完整的？

**Comment by Mondayfirst** [comment]
@git898989 2022年3月30日完整答完的，有可能这两天又新加了几道题目，学习强国每星期都在加题目。

**Comment by Mondayfirst** [comment]
@git898989 现在你可以自己建立本地题库。

**Comment by git898989** [comment]
@Mondayfirst 已给STAR, 不会JAVA编程，就老老实实下载题库了，题库也是每天更新吗

**Comment by wangwang-code** [comment]
> @Mondayfirst 已给STAR, 不会JAVA编程，就老老实实下载题库了，题库也是每天更新吗

js不像java那样复杂，很多js都已经给你想好了 我基本都是边看(教程)[https://www.runoob.com/js/js-tutorial.html]遍改Study 另外，作者已经开源刷挑战答题的脚本了

**Comment by git898989** [comment]
> > @Mondayfirst 已给STAR, 不会JAVA编程，就老老实实下载题库了，题库也是每天更新吗
> 
> js不像java那样复杂，很多js都已经给你想好了 我基本都是边看(教程)[https://www.runoob.com/js/js-tutorial.html]遍改Study 另外，作者已经开源刷挑战答题的脚本了

谢谢，我看看视频试试

**Comment by git898989** [comment]
@wangwang-code ,你好，问下，是不是在手机上安装Auto.js，然后在手机上运行主程序，手机里就有题库了，谢谢

**Comment by wangwang-code** [comment]
> @wangwang-code ,你好，问下，是不是在手机上安装Auto.js，然后在手机上运行主程序，手机里就有题库了，谢谢

1. 需要手动修改`var query_mode = "Server"` 为 `var query_mode = "Json"`

2. 将` var tk_path = "我的题库.json"`的路径修改为绝对路径，如`/sdcard/我的题库.json`

3. 手动下载题库json文件复制到你填写的地址路径下，
如`/sdcard/我的题库.json`  *`/sdcard/`在不插外置储存(SD卡)的情况下会被安卓定向到手机内部存储* 
需要将下载的json文件复制到手机内部储存的根目录并且重名为`我的题库.json`

ps:除使用auto.js 还可以使用hamibot这类基于auto.js的
